"""empty message

Revision ID: 240ea09ac5c4
Revises: 6a7dde4baeeb
Create Date: 2021-03-11 19:35:45.622772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240ea09ac5c4'
down_revision = '6a7dde4baeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'email')
    op.drop_column('business', 'person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('person', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('business', sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
