"""empty message

<<<<<<< HEAD:migrations/versions/57feec6cb301_.py
Revision ID: 57feec6cb301
Revises: 
Create Date: 2021-02-15 19:09:48.800228
=======
Revision ID: 6c80d9493e89
Revises: 
Create Date: 2021-02-15 19:09:49.067123
>>>>>>> 117d7d8b4a918c6e83ce0630dfae25af6d52b96b:migrations/versions/6c80d9493e89_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/57feec6cb301_.py
revision = '57feec6cb301'
=======
revision = '6c80d9493e89'
>>>>>>> 117d7d8b4a918c6e83ce0630dfae25af6d52b96b:migrations/versions/6c80d9493e89_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
