"""empty message

Revision ID: 9828eb686069
Revises: 8e428361b049
Create Date: 2021-03-13 18:48:07.347797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9828eb686069'
down_revision = '8e428361b049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
