"""empty message

Revision ID: beb4e716b9bd
Revises: 8fa717429312
Create Date: 2021-02-25 18:49:48.051654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb4e716b9bd'
down_revision = '8fa717429312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designation', sa.Column('name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designation', 'name')
    # ### end Alembic commands ###
